from selenium.webdriver.common.by import By

ID = By.ID
XPATH = By.XPATH
LINK_TEXT = By.LINK_TEXT
PARTIAL_LINK_TEXT = By.PARTIAL_LINK_TEXT
NAME = By.NAME
TAG_NAME = By.TAG_NAME
CLASS_NAME = By.CLASS_NAME
CSS_SELECTOR = By.CSS_SELECTOR
