Browser:
  chromium_executable_path: null
  chromium_profile_path: "{{SCRIPT_DIR}}/temp"
  downloads_path: "{{SCRIPT_DIR}}/temp/Downloads"
  session_path: "{{SCRIPT_DIR}}/temp/session.pickle"
  screenshots_path: "{{SCRIPT_DIR}}/temp/Screenshots"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
  global_timeout: 5  # Seconds.
  headless: false
  sandbox: true
  start_maximized: false
  quit_when_done: false
  debug_on_exception: true  # Start interactive debugger after encountering an exception.
  disable_selenium_logging: true  # Prevent selenium from polluting the terminal/log.
  disable_wdm_logging: true  # Prevent webdriver-manager from polluting the terminal/log.
  kill_chromium_before_start: false  # Kill any existing chromium processes before starting a new one.
  kill_wd_before_start: false  # Kill any existing webdriver processes before starting a new one.

Logging:
  log_path: "{{SCRIPT_DIR}}/temp/selenium.log"
  level: INFO  # DEBUG / INFO / WARNING / ERROR / CRITICAL.
  log_exceptions: true
  display_stdout: true
  mode: APPEND  # APPEND to append events to an existing log / WRITE to create a new file every run.
